### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by thecodeduchess** [CesBear/prj-rev-bwfs-dasmoto#1]
Hey, your readme isn't too detailed but it was awesome for you to include it. 

In the future, as your projects become more involved, you may want to elaborate on your readme. Explain what the app does, how to use it, how to get it running, if it's a web application.  :)

**Comment by CesBear** [comment]
Thank you for your comments, I will be mroe detailed in the next project, Also I will start to check Markdown to have a more styled README. Thanks!
