### ISSUE TITLE
Images 

### ISSUE THREAD

**Issue by thecodeduchess** [CesBear/prj-rev-bwfs-dasmoto#2]
https://github.com/CesBear/prj-rev-bwfs-dasmoto/blob/bb95f24537714637daaea769aa535955d9dd7b86/DasmotoProject/index.html#L14

Images properly linked and viewable. 
 
In the future, you will learn how to host these picture files and resources locally within your project.
The benefit of that is, your project will always be online if the site hosting your images is down.

**Comment by CesBear** [comment]
I was unsure if in this project I need it to save it locally, how ever makes sense taht if you include it in your project the images will always be up! Thanks for this tip!
